import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  cardList: {
    flexDirection: "row",
    position: "absolute",
    bottom: 12,
    left: 20,
    height: 110,
    width: "90%",
    backgroundColor: "#d3d3d3",
    borderRadius: 10,
  },
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  deckPile: {
    position: "absolute",
    width: 74,
    height: 108,
    backgroundColor: "#ADD8E6",
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "black",
    left: "25%",
    top: 160,
  },
  deckPileBackground: {
    position: "absolute",
    width: 74,
    height: 108,
    backgroundColor: "gray",
    // opacity: 0.3,
    borderRadius: 10,
    right: 23,
    bottom: 120,
  },
  discardPile: {
    position: "absolute",
    width: 74,
    height: 108,
    backgroundColor: "black",
    opacity: 0.3,
    borderRadius: 10,
    right: "25%",
    top: 160,
  },
  endTurnButton: {
    position: "absolute",
    width: 108,
    height: 33,
    borderWidth: 1,
    borderColor: "black",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    top: 75,
    right: "36.5%",
    zIndex: 10,
  },
  text: {
    font: 12,
    color: "red",
  },
  piles: {
    position: "absolute",
    width: "45%",
    height: "20%",
    backgroundColor: "black",
    opacity: 0.3,
    borderRadius: 10,
  },
  pileOne: {
    left: 12,
  },
  pileTwo: {
    right: 12,
  },
  pileThree: {
    left: 12,
    top: 475,
  },
  pileFour: {
    right: 12,
    top: 475,
  },
  test: {
    height: 5,
    width: 5,
    position: "absolute",
    backgroundColor: "green",
    left: 12,
    top: 309.33,
  },
  testtwo: {
    height: 5,
    width: 5,
    position: "absolute",
    backgroundColor: "green",
    left: 12,
    top: 463.663312988,
  },
});

export default styles;
